services:
  speculos:
    image: ghcr.io/ledgerhq/speculos
    volumes:
      - ${APP_ELF:-./tests/elf/app-iota-nanosp.elf}:/speculos/app.elf:ro
    ports:
      - "9999:9999"
      - "5000:5000"
    command:
      - --model
      - ${SPECULOS_MODEL:-nanosp}
      - --display
      - headless
      - --apdu-port
      - "9999"
      - --api-port
      - "5000"
      - --seed
      - "glory promote mansion idle axis finger extra february uncover one trip resource lawn turtle enact monster seven myth punch hobby comfort wild raise skin"
      - /speculos/app.elf
